version: '3'
services:
    mongodb:
        image: 'mongo:latest'
        ports:
            - 27017:27017
    graphql-server:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        command: npm start
        ports:
            - 4000:4000
        depends_on:
            - mongodb
        environment:
            - mongoURI=mongodb://mongodb:27017/graphql-development
    react:
        image: node:10-alpine
        ports:
            - '7070:7070'
            - '7777:7777'
        environment:
            - NODE_ENV=dev
        working_dir: /var/app/assets
        command: npm run start
        volumes:
            - ./:/var/app/assets
